version: "3.8"

services:
  chroma:
    image: chromadb/chroma:latest
    container_name: chroma_db
    ports:
      - "8000:8000"  # Expose to host and Docker network
    volumes:
      - chroma_data:/chroma/.chroma/index
    environment: {}
    restart: unless-stopped

  chroma_mcp_server:
    build:
      context: ./chroma_mcp_server
    container_name: chroma_mcp_server
    environment:
      CHROMA_HOST: chroma
      CHROMA_PORT: 8000
    depends_on:
      - chroma
    # No ports exposed; communicates via STDIO when run by RooCode
    restart: unless-stopped

volumes:
  chroma_data:
    driver: local

# Usage:
#   docker compose up -d
#   ChromaDB will be available at http://localhost:8000 and to other containers in the network.